[package]
name = "livelocd"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.7", features = ["ws"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
once_cell = "1.19"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
hyper = "1.6.0"

